window.PANTRY_STAPLES = {
    "Baking Extras": [
        "cake crumbs",
        "chocolate chips",
        "chocolate sprinkles",
        "cocoa powder",
        "custard powder",
        "dark choc bits",
        "dark chocolate",
        "dark chocolate chips",
        "dark chocolate melts",
        "food colouring",
        "gelatine leaves",
        "gelatine powder",
        "glucose syrup",
        "milk choc bits",
        "natural vanilla extract",
        "vanilla essence",
        "white chocolate",
        "white chocolate chips"
    ],
    "Bread Bakery": [
        "breadcrumbs",
        "frozen puff pastry",
        "naan bread",
        "puff pastry",
        "shortcrust pastry",
        "sourdough starter"
    ],
    "Butter Dairy": [
        "butter",
        "ghee",
        "salted butter",
        "spreadable butter",
        "unsalted butter"
    ],
    "Canned Fish Seafood": [
        "anchovies",
        "fish fillet",
        "fresh oysters",
        "oysters",
        "prawns",
        "salmon",
        "sardines",
        "seafood mix",
        "tuna in brine"
    ],
    "Canned Fruit": [
        "apple slices",
        "apricot halves",
        "crushed pineapple",
        "peach slices",
        "pineapple chunks",
        "pineapple pieces",
        "pineapple rings",
        "pineapple slices"
    ],
    "Canned Tomatoes": [
        "crushed tomatoes",
        "diced tomatoes",
        "passata",
        "peeled tomatoes",
        "tomato paste",
        "tomato puree",
        "tomato soup",
        "tomatoes"
    ],
    "Cheese": [
        "blue cheese",
        "bocconcini",
        "camembert cheese",
        "cheddar cheese",
        "cottage cheese",
        "cream cheese",
        "extra tasty cheese",
        "feta",
        "gruyere",
        "haloumi",
        "mascarpone",
        "mozzarella",
        "mozzarella cheese",
        "parmesan",
        "parmesan cheese",
        "parmesan shaved",
        "philadelphia cream cheese",
        "ricotta",
        "ricotta cheese",
        "shredded parmesan",
        "tasty cheese",
        "tasty cheese block",
        "vintage cheddar"
    ],
    "Dried Fruit Nuts": [
        "almonds",
        "brazil nuts",
        "cashews",
        "cranberries",
        "dates",
        "apricots",
        "hazelnuts",
        "macadamia nuts",
        "pecans",
        "pine nuts",
        "pistachios",
        "raisins",
        "sultanas",
        "walnuts"
    ],
    "Drinks Alcohol": [
        "beer",
        "brandy",
        "chinese rice wine",
        "coffee",
        "gin",
        "grand marnier",
        "instant coffee",
        "red wine",
        "rum",
        "tia maria",
        "vodka",
        "whiskey",
        "white wine"
    ],
    "Eggs": [
        "egg whites",
        "egg yolks",
        "eggs"
    ],
    "Flour Baking": [
        "almond meal",
        "bakers flour",
        "bran",
        "bread flour",
        "bread improver",
        "buckwheat flour",
        "cornflour",
        "gluten free plain flour",
        "plain flour",
        "rye flour",
        "self-raising flour",
        "tapioca flour",
        "vital wheat gluten"
    ],
    "Fresh Fruit": [
        "apricot",
        "apricot nectar",
        "black grapes",
        "blackberries",
        "blueberries",
        "calamansi",
        "cherries",
        "dragon fruit",
        "grapes",
        "kiwi fruit",
        "kiwifruit",
        "mandarin",
        "mango",
        "nectarine",
        "orange",
        "passionfruit",
        "peach",
        "pineapple",
        "plum",
        "raspberries",
        "red grapes",
        "strawberries",
        "white grapes"
    ],
    "Fresh Herbs": [
        "coriander leaves",
        "basil",
        "chives",
        "coriander",
        "dill",
        "mint",
        "oregano",
        "parsley",
        "rosemary",
        "sage",
        "thyme"
    ],
    "Fresh Vegetables": [
        "Ginger",
        "apple",
        "apple juice",
        "apples",
        "asparagus",
        "avocado",
        "baby carrots",
        "baby spinach",
        "banana",
        "bananas",
        "basil leaves",
        "beetroot",
        "bravo apple",
        "broccoli",
        "brown onion",
        "brushed potato",
        "butternut pumpkin",
        "cabbage",
        "capsicum",
        "carrot",
        "carrots",
        "cauliflower",
        "cavendish banana",
        "celery",
        "cherry tomatoes",
        "corn cobs",
        "corn on cob",
        "cucumber",
        "dried red chilli",
        "fresh ginger",
        "garlic",
        "garlic cloves",
        "gourmet tomato",
        "granny smith apples",
        "green beans",
        "green capsicum",
        "green chilli",
        "iceberg lettuce",
        "jalapeno",
        "jalapenos",
        "kent pumpkin",
        "lebanese cucumber",
        "leek",
        "lemon",
        "lemon juice",
        "lime juice",
        "long green chilli",
        "long red chilli",
        "mushrooms",
        "onion",
        "pickled jalapenos",
        "pineapple juice",
        "pink lady apple",
        "potato",
        "potatoes",
        "pumpkin",
        "radish",
        "red capsicum",
        "red cayenne chilli",
        "red chilli",
        "roasting potatoes",
        "savoy cabbage",
        "shallot",
        "shallots",
        "sliced beetroot",
        "sliced mushrooms",
        "snow peas",
        "spanish onion",
        "spinach",
        "spring onion",
        "sugar snap peas",
        "sweet potato",
        "tomato",
        "truss tomatoes",
        "watermelon",
        "whole pumpkin",
        "zucchini"
    ],
    "Meat Poultry": [
        "beef bones",
        "beef knuckles",
        "beef mince",
        "beef sausages",
        "beef scraps",
        "beef shanks",
        "beef strips",
        "champagne ham",
        "chicken breast",
        "chicken drumsticks",
        "chicken kebab",
        "chicken maryland",
        "chicken schnitzel",
        "chicken thigh",
        "chicken thigh cutlets",
        "chicken thigh fillets",
        "chinese sausage",
        "cocktail frankfurts",
        "diced beef",
        "diced lamb",
        "frankfurts",
        "ham",
        "hot dogs",
        "lamb cutlets",
        "lamb forequarter chops",
        "lamb leg roast",
        "lamb rack",
        "lamb strips",
        "leg ham",
        "middle bacon",
        "pepperoni",
        "pork chops",
        "pork leg roast",
        "pork mince",
        "pork shoulder",
        "pork strips",
        "prosciutto",
        "rump steak",
        "salami",
        "scotch fillet",
        "shredded ham",
        "veal"
    ],
    "Milk Cream": [
        "buttermilk",
        "coconut cream",
        "coconut milk",
        "cooking cream",
        "milk full-cream",
        "milk skim",
        "milk powder full-cream",
        "milk powder skim",
        "pure cream",
        "sour cream",
        "thickened cream"
    ],
    "Oils": [
        "coconut oil",
        "olive oil",
        "peanut oil",
        "sesame oil",
        "sunflower oil",
        "vegetable oil"
    ],
    "Pasta Noodles": [
        "bihon rice noodles",
        "canton egg noodles",
        "egg noodles",
        "elbows pasta",
        "fettuccine",
        "instant noodles",
        "lasagne sheets",
        "mi goreng noodles",
        "spaghetti",
        "vermicelli rice noodles"
    ],
    "Rice Grains": [
        "arborio rice",
        "basmati rice",
        "black quinoa",
        "bulgur wheat",
        "freekeh",
        "jasmine rice",
        "quinoa",
        "rolled oats",
        "white quinoa",
        "white rice"
    ],
    "Sauces Condiments": [
        "american mustard",
        "apple cider vinegar",
        "apricot jam",
        "australian mustard",
        "balsamic vinegar",
        "barbecue sauce",
        "bbq sauce",
        "brown vinegar",
        "chilli sauce",
        "dark soy sauce",
        "demi glace",
        "dijon mustard",
        "fish sauce",
        "green olives",
        "hoisin sauce",
        "hot english mustard",
        "kalamata olives",
        "kecap manis",
        "light soy sauce",
        "mayonnaise",
        "mild english mustard",
        "mint sauce",
        "mirin",
        "miso paste",
        "oyster sauce",
        "plum jam",
        "red curry paste",
        "rice wine vinegar",
        "sambal oelek",
        "seafood cocktail sauce",
        "soy sauce",
        "sriracha",
        "sweet & sour sauce",
        "sweet chilli sauce",
        "tartare sauce",
        "tomato ketchup",
        "tomato sauce",
        "white vinegar",
        "wholegrain mustard",
        "worcestershire sauce"
    ],
    "Seeds Superfoods": [
        "black chia seeds",
        "flaxseed meal",
        "gentle fibre",
        "hemp protein powder",
        "hemp seeds",
        "linseed",
        "psyllium husk",
        "pumpkin kernels",
        "soy lecithin",
        "sunflower seeds",
        "white chia seeds",
        "xanthan gum"
    ],
    "Snacks Biscuits": [
        "arnotts butternut snap cookies",
        "arnotts nice biscuits",
        "butternut snap cookies",
        "nice biscuits",
        "oreos",
        "tim tams"
    ],
    "Spices Seasonings": [
        "achiote powder",
        "allspice",
        "baking powder",
        "bay leaves",
        "bi-carb soda",
        "black pepper",
        "black peppercorns",
        "cajun seasoning",
        "ground cardamom",
        "cardamom pods",
        "cayenne pepper",
        "chicken salt",
        "chicken seasoning",
        "chilli dried crushed",
        "chilli flakes",
        "chilli powder",
        "chinese five spice",
        "chives",
        "ground cinnamon",
        "cinnamon stick",
        "ground cloves",
        "cloves whole",
        "coriander seeds",
        "cumin seeds",
        "curry powder",
        "desiccated coconut",
        "dill",
        "fennel seeds",
        "fenugreek",
        "fenugreek seeds",
        "garam masala",
        "garlic powder",
        "green cardamom pods",
        "green peppercorns",
        "ground coriander",
        "ground cumin",
        "ground ginger",
        "italian herbs",
        "mixed herbs",
        "mixed spice",
        "moroccan spice",
        "nigella seeds",
        "ground nutmeg",
        "onion powder",
        "oregano",
        "ground paprika",
        "parsley",
        "poppy seeds",
        "red chilli flakes",
        "red chilli powder",
        "rosemary",
        "saffron",
        "sage",
        "salt",
        "sesame seeds",
        "smoked paprika",
        "sweet paprika",
        "star anise",
        "steak seasoning",
        "taco seasoning",
        "thyme leaves",
        "ground turmeric",
        "white pepper",
        "yeast"
    ],
    "Spreads": [
        "liver spread",
        "nutella",
        "peanut butter",
        "raspberry jam",
        "strawberry jam",
        "vegemite"
    ],
    "Stock Broth": [
        "beef stock",
        "beef stock cube",
        "chicken stock",
        "chicken stock cube",
        "gravy mix",
        "pork stock",
        "pork stock cube"
    ],
    "Sugar Sweeteners": [
        "brown sugar",
        "caster sugar",
        "condensed milk",
        "golden syrup",
        "honey",
        "icing sugar",
        "malt powder",
        "maple syrup",
        "molasses",
        "treacle",
        "white sugar"
    ],
    "Yoghurt": [
        "greek yoghurt",
        "natural yoghurt"
    ]
};
