/* =========================================================
   PANTRY STAPLES — KitchenNotebook Kitchen Notebook
   Auto-generated from recipe-prices.json
   505 ingredients across 27 categories
========================================================= */
window.PANTRY_STAPLES = {
    "Baking Extras": [
        "cake crumbs",
        "chocolate chips",
        "chocolate sprinkles",
        "cocoa powder",
        "custard powder",
        "dark choc bits",
        "dark chocolate",
        "dark chocolate chips",
        "dark chocolate melts",
        "food colouring",
        "gelatine",
        "milk choc bits",
        "natural vanilla extract",
        "organic vanilla extract",
        "vanilla",
        "vanilla essence",
        "white chocolate",
        "white chocolate chips"
    ],
    "Bread Bakery": [
        "breadcrumbs",
        "frozen puff pastry",
        "naan bread",
        "puff pastry",
        "shortcrust pastry",
        "sourdough starter"
    ],
    "Butter Dairy": [
        "butter",
        "ghee",
        "salted butter",
        "spreadable butter",
        "unsalted butter"
    ],
    "Canned Fish Seafood": [
        "anchovies",
        "fish fillet",
        "fresh oysters",
        "oysters",
        "prawns",
        "salmon",
        "sardines",
        "seafood mix",
        "tuna in brine"
    ],
    "Canned Fruit": [
        "apple slices",
        "apricot halves",
        "canned apricot halves",
        "canned pineapple rings",
        "crushed pineapple",
        "peach slices",
        "pineapple chunks",
        "pineapple pieces",
        "pineapple slices"
    ],
    "Canned Tomatoes": [
        "crushed tomatoes",
        "diced tomatoes",
        "diced tomatoes basil & oregano",
        "passata",
        "peeled tomatoes",
        "tomato paste",
        "tomato puree",
        "tomato soup",
        "tomatoes"
    ],
    "Cheese": [
        "blue cheese",
        "bocconcini",
        "camembert cheese",
        "cheddar cheese",
        "cottage cheese",
        "cream cheese",
        "extra tasty cheese",
        "feta",
        "gruyere",
        "haloumi",
        "mascarpone",
        "mozzarella",
        "mozzarella cheese",
        "parmesan",
        "parmesan cheese",
        "parmesan shaved",
        "philadelphia cream cheese",
        "ricotta",
        "ricotta cheese",
        "shredded parmesan",
        "tasty cheese",
        "tasty cheese block",
        "vintage cheddar"
    ],
    "Dried Fruit Nuts": [
        "almonds",
        "brazil nuts",
        "cashews",
        "cranberries",
        "dates",
        "dried apricots",
        "hazelnuts",
        "macadamia nuts",
        "pecans",
        "pine nuts",
        "pistachios",
        "raisins",
        "sultanas",
        "walnuts"
    ],
    "Drinks Alcohol": [
        "beer",
        "brandy",
        "chinese rice wine",
        "coffee",
        "gin",
        "grand marnier",
        "instant coffee",
        "red wine",
        "rum",
        "tia maria",
        "vodka",
        "whiskey",
        "white wine"
    ],
    "Eggs": [
        "egg",
        "egg whites",
        "egg yolk",
        "egg yolks",
        "eggs"
    ],
    "Flour Baking": [
        "almond meal",
        "bran",
        "bread flour",
        "buckwheat flour",
        "cornflour",
        "gluten free plain flour",
        "plain flour",
        "rye flour",
        "self raising flour",
        "self-raising flour",
        "tapioca flour",
        "vital wheat gluten"
    ],
    "Fresh Fruit": [
        "apple juice",
        "apricot",
        "apricot nectar",
        "black grapes",
        "blackberries",
        "blueberries",
        "calamansi",
        "cherries",
        "dragon fruit",
        "grapes",
        "kiwi fruit",
        "kiwifruit",
        "mango",
        "mango nectar",
        "nectarine",
        "orange",
        "orange juice",
        "orange zest",
        "passionfruit",
        "peach",
        "pineapple",
        "pineapple juice",
        "plum",
        "raspberries",
        "red grapes",
        "strawberries",
        "white grapes"
    ],
    "Fresh Herbs": [
        "coriander leaves",
        "fresh basil",
        "fresh chives",
        "fresh coriander",
        "fresh dill",
        "fresh mint",
        "fresh oregano",
        "fresh parsley",
        "fresh rosemary",
        "fresh sage",
        "fresh thyme",
        "parsley leaves"
    ],
    "Fresh Vegetables": [
        "Brown Onions",
        "Ginger",
        "apple",
        "apples",
        "asparagus",
        "avocado",
        "baby carrots",
        "baby spinach",
        "banana",
        "bananas",
        "basil leaves",
        "beetroot",
        "bravo apple",
        "broccoli",
        "brown onion",
        "brushed potato",
        "butternut pumpkin",
        "cabbage",
        "capsicum",
        "carrot",
        "carrots",
        "cauliflower",
        "cavendish banana",
        "celery",
        "cherry tomatoes",
        "corn cobs",
        "corn on cob",
        "cucumber",
        "dried red chilli",
        "dried red chillies",
        "fresh ginger",
        "garlic",
        "garlic cloves",
        "gourmet tomato",
        "granny smith apple",
        "granny smith apples",
        "green beans",
        "green capsicum",
        "green chilli",
        "green chillies",
        "iceberg lettuce",
        "jalapeno",
        "jalapeno chilli",
        "jalapenos",
        "jalapeño",
        "jalapeños",
        "kent pumpkin",
        "lebanese cucumber",
        "leek",
        "lemon",
        "lemon juice",
        "lemon zest",
        "lime juice",
        "long green chilli",
        "long red chilli",
        "mandarin",
        "mini roma tomatoes",
        "mushrooms",
        "mushrooms punnet 500g",
        "onion",
        "pickled jalapenos",
        "pickled jalapeños",
        "pink lady apple",
        "potato",
        "potatoes",
        "pumpkin",
        "radish",
        "red capsicum",
        "red cayenne chilli",
        "red chilli",
        "roasting potatoes",
        "savoy cabbage",
        "shallot",
        "shallots",
        "sliced beetroot",
        "sliced mushrooms",
        "snow peas",
        "spinach",
        "spring onion",
        "sugar snap peas",
        "sweet potato",
        "tomato",
        "truss tomatoes",
        "watermelon",
        "whole pumpkin",
        "zucchini"
    ],
    "Meat Poultry": [
        "Chicken Drum Sticks",
        "bacon",
        "beef",
        "beef bones",
        "beef knuckles",
        "beef mince",
        "beef mince 500g",
        "beef sausages",
        "beef scraps",
        "beef shanks",
        "beef, scotch fillet",
        "champagne ham",
        "chicken breast",
        "chicken breast fillet 350g",
        "chicken breasts",
        "chicken drumsticks",
        "chicken kebab",
        "chicken maryland",
        "chicken schnitzel",
        "chicken thigh",
        "chicken thigh cutlets",
        "chicken thigh fillet",
        "chicken thigh fillets",
        "chinese sausage",
        "cocktail frankfurts",
        "frankfurts",
        "ham",
        "hans middle bacon",
        "hot dogs",
        "lamb",
        "lamb cutlets",
        "lamb forequarter chops",
        "lamb leg roast",
        "lamb rack",
        "leg ham",
        "middle bacon",
        "pepperoni",
        "pork",
        "pork chops",
        "pork leg roast",
        "pork mince",
        "pork shoulder",
        "prosciutto",
        "rump steak",
        "salami",
        "scotch fillet",
        "shredded ham",
        "veal"
    ],
    "Milk Cream": [
        "buttermilk",
        "coconut cream",
        "coconut milk",
        "cooking cream",
        "cream",
        "heavy cream",
        "milk",
        "milk powder",
        "pure cream",
        "sour cream",
        "thickened cream"
    ],
    "Oils": [
        "coconut oil",
        "olive oil",
        "peanut oil",
        "sesame oil",
        "sunflower oil",
        "vegetable oil"
    ],
    "Pasta Noodles": [
        "bihon rice noodles",
        "canton egg noodles",
        "egg noodles",
        "elbows pasta",
        "fettuccine",
        "instant noodles",
        "lasagne sheets",
        "mi goreng noodles",
        "spaghetti",
        "vermicelli rice noodles"
    ],
    "Rice Grains": [
        "arborio rice",
        "basmati rice",
        "black quinoa",
        "bulgur wheat",
        "freekeh",
        "jasmine rice",
        "quinoa",
        "rolled oats",
        "white quinoa",
        "white rice"
    ],
    "Sauces Condiments": [
        "apple cider vinegar",
        "apricot jam",
        "australian mustard",
        "balsamic vinegar",
        "barbecue sauce",
        "bbq sauce",
        "chilli garlic sauce",
        "chilli sauce",
        "curry paste",
        "dark soy sauce",
        "demi glace",
        "dijon mustard",
        "fish sauce",
        "green curry paste",
        "hoisin sauce",
        "hot english mustard",
        "kalamata olives",
        "kecap manis",
        "light soy sauce",
        "mayonnaise",
        "mild english mustard",
        "mint sauce",
        "mirin",
        "miso paste",
        "mustard",
        "oyster sauce",
        "plum jam",
        "red curry paste",
        "rice vinegar",
        "sambal oelek",
        "seafood cocktail sauce",
        "soy sauce",
        "sriracha",
        "sriracha sauce",
        "sweet & sour sauce",
        "sweet chilli sauce",
        "tartare sauce",
        "tomato ketchup",
        "tomato sauce",
        "vinegar",
        "white vinegar",
        "wholegrain mustard",
        "worcestershire sauce"
    ],
    "Seeds Superfoods": [
        "black chia seeds",
        "chia seeds",
        "flaxseed meal",
        "hemp protein powder",
        "hemp seeds",
        "linseed",
        "psyllium husk",
        "pumpkin kernels",
        "pumpkin seeds",
        "soy lecithin",
        "soy lecithin granules",
        "sunflower kernels",
        "sunflower seeds",
        "white chia seeds",
        "xanthan gum"
    ],
    "Snacks Biscuits": [
        "arnotts butternut snap cookies",
        "arnotts nice biscuits",
        "butternut snap cookies",
        "nice biscuits",
        "oreos",
        "tim tams"
    ],
    "Spices Seasonings": [
        "achiote powder",
        "allspice",
        "baking powder",
        "baking soda",
        "bay leaves",
        "bi-carb soda",
        "bicarb soda",
        "bicarbonate of soda",
        "black pepper",
        "black peppercorns",
        "bread improver",
        "cajun seasoning",
        "cardamom",
        "cardamom pods",
        "cayenne pepper",
        "chicken salt",
        "chicken seasoning",
        "chilli dried crushed",
        "chilli flakes",
        "chilli powder",
        "chinese 5 spice",
        "chinese five spice",
        "chives",
        "cinnamon",
        "cinnamon stick",
        "cloves",
        "cloves ground",
        "cloves whole",
        "coriander",
        "coriander seeds",
        "cumin",
        "cumin seeds",
        "curry powder",
        "desiccated coconut",
        "dill",
        "fennel seeds",
        "fenugreek",
        "fenugreek seeds",
        "garam masala",
        "garlic powder",
        "green cardamom pods",
        "green peppercorns",
        "ground coriander",
        "ground cumin",
        "ground ginger",
        "himalayan pink salt",
        "italian herb mix",
        "italian herbs",
        "mint leaves",
        "mixed herbs",
        "moroccan spice",
        "nigella seeds",
        "nutmeg",
        "onion powder",
        "oregano",
        "paprika",
        "parsley",
        "poppy seed",
        "poppy seeds",
        "red chilli flakes",
        "red chilli powder",
        "rosemary",
        "saffron",
        "sage",
        "salt",
        "sea salt flakes",
        "sesame seeds",
        "smoked paprika",
        "star anise",
        "steak seasoning",
        "table salt",
        "taco seasoning",
        "thyme",
        "thyme leaves",
        "turmeric",
        "white pepper",
        "yeast"
    ],
    "Spreads": [
        "liver spread",
        "nutella",
        "peanut butter",
        "raspberry jam",
        "strawberry jam",
        "vegemite"
    ],
    "Stock Broth": [
        "beef stock",
        "beef stock cubes",
        "chicken stock",
        "chicken stock cube",
        "chicken stock cubes",
        "gravy mix",
        "pork stock",
        "pork stock cube"
    ],
    "Sugar Sweeteners": [
        "brown sugar",
        "caster sugar",
        "condensed milk",
        "golden syrup",
        "honey",
        "icing sugar",
        "light brown sugar",
        "malt powder",
        "maple syrup",
        "molasses",
        "pure icing sugar",
        "white sugar"
    ],
    "Yoghurt": [
        "greek yoghurt",
        "greek yogurt",
        "natural yoghurt",
        "natural yogurt",
        "yogurt"
    ]
};
