window.PANTRY_STAPLES = {
    "Baking Extras": [
        "cake crumbs",
        "chocolate dark",
        "chocolate dark bits",
        "chocolate dark chips",
        "chocolate dark melts",
        "chocolate milk bits",
        "chocolate milk chips",
        "chocolate sprinkles",
        "chocolate white",
        "chocolate white chips",
        "cocoa powder",
        "custard powder",
        "food colouring",
        "gelatine leaves",
        "gelatine powder",
        "glucose syrup",
        "vanilla essence",
        "vanilla extract natural"
    ],
    "Bread Bakery": [
        "bread naan",
        "breadcrumbs",
        "pastry puff",
        "pastry puff frozen",
        "pastry shortcrust",
        "sourdough starter"
    ],
    "Butter Dairy": [
        "butter salted",
        "butter spreadable",
        "butter unsalted",
        "ghee"
    ],
    "Canned Fish Seafood": [
        "anchovies",
        "fish fillet",
        "oysters canned",
        "oysters fresh",
        "prawns",
        "salmon",
        "sardines",
        "seafood mix",
        "tuna in brine"
    ],
    "Canned Fruit": [
        "apple slices",
        "apricot halves",
        "pineapple chunks",
        "pineapple crushed",
        "pineapple pieces",
        "pineapple rings",
        "pineapple slices"
    ],
    "Canned Tomatoes": [
        "tomato crushed",
        "tomato diced",
        "tomato passata",
        "tomato paste",
        "tomato peeled",
        "tomato puree",
        "tomato soup",
        "tomato whole"
    ],
    "Cheese": [
        "cheese blue",
        "cheese bocconcini",
        "cheese camembert",
        "cheese cheddar",
        "cheese cheddar vintage",
        "cheese cottage",
        "cheese cream",
        "cheese feta",
        "cheese gruyere",
        "cheese haloumi",
        "cheese mascarpone",
        "cheese mozzarella",
        "cheese parmesan",
        "cheese parmesan shaved",
        "cheese parmesan shredded",
        "cheese ricotta",
        "cheese tasty",
        "cheese tasty block"
    ],
    "Dried Fruit Nuts": [
        "apricots dried",
        "cranberries dried",
        "dates",
        "nuts almonds",
        "nuts brazil",
        "nuts cashews",
        "nuts hazelnuts",
        "nuts macadamia",
        "nuts pecans",
        "nuts pine",
        "nuts pistachios",
        "nuts walnuts",
        "raisins",
        "sultanas"
    ],
    "Drinks Alcohol": [
        "beer",
        "brandy",
        "coffee",
        "coffee instant",
        "gin",
        "grand marnier",
        "rum",
        "tia maria",
        "vodka",
        "whiskey",
        "wine chinese rice",
        "wine red",
        "wine white"
    ],
    "Eggs": [
        "eggs white",
        "eggs whole",
        "eggs yolk"
    ],
    "Flour Baking": [
        "almond meal",
        "bran",
        "bread improver",
        "cornflour",
        "flour bakers",
        "flour bread",
        "flour buckwheat",
        "flour gluten free plain",
        "flour plain",
        "flour rye",
        "flour self-raising",
        "flour tapioca",
        "vital wheat gluten"
    ],
    "Fresh Fruit": [
        "apricot",
        "apricot nectar",
        "blackberries",
        "blueberries",
        "calamansi",
        "cherries",
        "dragon fruit",
        "grapes black",
        "grapes red",
        "grapes white",
        "kiwifruit",
        "mandarin",
        "mango",
        "nectarine",
        "orange",
        "passionfruit",
        "peach",
        "pineapple",
        "plum",
        "raspberries",
        "strawberries"
    ],
    "Fresh Herbs": [
        "basil",
        "chives",
        "coriander",
        "dill",
        "mint",
        "oregano",
        "parsley",
        "rosemary",
        "sage",
        "thyme"
    ],
    "Fresh Vegetables": [
        "apple bravo",
        "apple granny smith",
        "apple juice",
        "apple pink lady",
        "apple whole",
        "asparagus",
        "avocado",
        "banana",
        "banana cavendish",
        "beans green",
        "beetroot",
        "beetroot sliced",
        "broccoli",
        "cabbage",
        "cabbage savoy",
        "capsicum green",
        "capsicum red",
        "carrot",
        "carrot baby",
        "cauliflower",
        "celery",
        "chilli dried red",
        "chilli green",
        "chilli long green",
        "chilli long red",
        "chilli red",
        "chilli red cayenne",
        "corn cob",
        "cucumber",
        "cucumber lebanese",
        "garlic",
        "ginger fresh",
        "jalapeno fresh",
        "jalapeno pickled",
        "leek",
        "lemon",
        "lemon juice",
        "lettuce iceberg",
        "lime juice",
        "mushrooms",
        "mushrooms sliced",
        "onion brown",
        "onion red spanish",
        "onion spring",
        "peas snow",
        "peas sugar snap",
        "pineapple juice",
        "potato brushed",
        "potato roasting",
        "potato sweet",
        "potato white",
        "pumpkin butternut",
        "pumpkin kent",
        "pumpkin whole",
        "radish",
        "shallots",
        "spinach",
        "spinach baby",
        "tomato cherry",
        "tomato gourmet",
        "tomato truss",
        "tomato whole",
        "watermelon",
        "zucchini"
    ],
    "Meat Poultry": [
        "bacon middle",
        "beef bones",
        "beef diced",
        "beef knuckles",
        "beef mince",
        "beef sausages",
        "beef scraps",
        "beef shanks",
        "beef steak rump",
        "beef steak scotch fillet",
        "beef strips",
        "chicken breast",
        "chicken drumsticks",
        "chicken kebab",
        "chicken maryland",
        "chicken schnitzel",
        "chicken thigh",
        "chicken thigh cutlets",
        "chicken thigh fillets",
        "frankfurts",
        "frankfurts cocktail",
        "ham champagne",
        "ham leg",
        "ham shredded",
        "hot dogs",
        "lamb cutlets",
        "lamb diced",
        "lamb forequarter chops",
        "lamb leg roast",
        "lamb rack",
        "lamb strips",
        "pepperoni",
        "pork chops",
        "pork leg roast",
        "pork mince",
        "pork shoulder",
        "pork strips",
        "prosciutto",
        "salami",
        "sausage chinese",
        "veal"
    ],
    "Milk Cream": [
        "buttermilk",
        "coconut cream",
        "coconut milk",
        "cream cooking",
        "cream pure",
        "cream sour",
        "cream thickened",
        "milk full-cream",
        "milk powder full-cream",
        "milk powder skim",
        "milk skim"
    ],
    "Oils": [
        "oil coconut",
        "oil olive",
        "oil peanut",
        "oil sesame",
        "oil sunflower",
        "oil vegetable"
    ],
    "Pasta Noodles": [
        "noodles bihon rice",
        "noodles canton egg",
        "noodles egg",
        "noodles instant",
        "noodles mi goreng",
        "noodles vermicelli rice",
        "pasta elbows",
        "pasta fettuccine",
        "pasta lasagne sheets",
        "pasta spaghetti"
    ],
    "Rice Grains": [
        "bulgur wheat",
        "freekeh",
        "quinoa black",
        "quinoa white",
        "rice arborio",
        "rice basmati",
        "rice jasmine",
        "rice white",
        "rolled oats"
    ],
    "Sauces Condiments": [
        "demi glace",
        "jam apricot",
        "jam plum",
        "mayonnaise",
        "mirin",
        "miso paste",
        "mustard american",
        "mustard australian",
        "mustard dijon",
        "mustard hot english",
        "mustard mild english",
        "mustard wholegrain",
        "olives green",
        "olives kalamata",
        "red curry paste",
        "sambal oelek",
        "sauce barbecue",
        "sauce chilli",
        "sauce fish",
        "sauce hoisin",
        "sauce kecap manis",
        "sauce mint",
        "sauce oyster",
        "sauce seafood cocktail",
        "sauce soy",
        "sauce soy dark",
        "sauce soy light",
        "sauce sweet & sour",
        "sauce sweet chilli",
        "sauce tartare",
        "sauce tomato",
        "sauce tomato ketchup",
        "sauce worcestershire",
        "sriracha",
        "vinegar apple cider",
        "vinegar balsamic",
        "vinegar brown",
        "vinegar rice wine",
        "vinegar white"
    ],
    "Seeds Superfoods": [
        "chia seeds black",
        "chia seeds white",
        "flaxseed meal",
        "gentle fibre",
        "hemp protein powder",
        "hemp seeds",
        "linseed",
        "psyllium husk",
        "pumpkin kernels",
        "soy lecithin",
        "sunflower seeds",
        "xanthan gum"
    ],
    "Snacks Biscuits": [
        "biscuits Nice Arnotts",
        "biscuits Tim Tams",
        "cookies butternut snap Arnotts",
        "cookies Oreos"
    ],
    "Spices Seasonings": [
        "achiote powder",
        "allspice",
        "baking powder",
        "bay leaves",
        "bi-carb soda",
        "cardamom green pods",
        "cardamom ground",
        "cardamom pods",
        "cayenne pepper",
        "chilli flakes",
        "chilli powder",
        "chilli powder red",
        "chilli red flakes",
        "chilli whole dried crushed",
        "chives",
        "cinnamon ground",
        "cinnamon stick",
        "cloves ground",
        "cloves whole",
        "coconut desiccated",
        "coriander ground",
        "coriander seeds",
        "cumin ground",
        "cumin whole",
        "curry powder",
        "dill",
        "fennel seeds",
        "fenugreek seeds",
        "five spice chinese",
        "garam masala",
        "garlic powder",
        "ginger ground",
        "herbs italian",
        "herbs mixed",
        "mixed spice",
        "moroccan spice",
        "nigella seeds",
        "nutmeg ground",
        "onion powder",
        "oregano",
        "paprika ground",
        "paprika smoked",
        "paprika sweet",
        "parsley",
        "pepper black ground",
        "pepper black peppercorns",
        "pepper green peppercorns",
        "pepper white ground",
        "poppy seeds",
        "rosemary",
        "saffron",
        "sage",
        "salt",
        "salt chicken",
        "seasoning cajun",
        "seasoning chicken",
        "seasoning steak",
        "seasoning taco",
        "sesame seeds",
        "star anise",
        "thyme leaves",
        "turmeric ground",
        "yeast"
    ],
    "Spreads": [
        "jam raspberry",
        "jam strawberry",
        "spread liver",
        "spread Nutella",
        "spread peanut butter",
        "spread Vegemite"
    ],
    "Stock Broth": [
        "gravy mix",
        "stock beef",
        "stock beef cube",
        "stock chicken",
        "stock chicken cube",
        "stock pork",
        "stock pork cube"
    ],
    "Sugar Sweeteners": [
        "condensed milk",
        "honey",
        "malt powder",
        "molasses",
        "sugar brown",
        "sugar caster",
        "sugar icing",
        "sugar white",
        "syrup golden",
        "syrup maple",
        "treacle"
    ],
    "Yoghurt": [
        "yoghurt greek"
    ]
};